Add comscripts module (#3738)

diff --git a/test/Makefile.am b/test/Makefile.am
--- a/test/Makefile.am
+++ b/test/Makefile.am
@@ -1,7 +1,7 @@
 #############################################################################
 # Makefile.am for ctools unit tests                                         #
 # ------------------------------------------------------------------------- #
-# Copyright (C) 2016-2017 Juergen Knoedlseder                               #
+# Copyright (C) 2016-2021 Juergen Knoedlseder                               #
 # ------------------------------------------------------------------------- #
 #                                                                           #
 #  This program is free software: you can redistribute it and/or modify     #
@@ -25,23 +25,25 @@ MACOSX_DEPLOYMENT_TARGET=@CONFIGURE_MACOSX_DEPLOYMENT_TARGET@
 
 # Optional python bindings
 if WITH_PYTHON
-  TEST_PYTHON_CTOOLS   = test_python_ctools.sh
-  TEST_PYTHON_CSCRIPTS = test_python_cscripts.sh
-  TEST_PYTHON_EXAMPLES = test_examples.py
-  TEST_PYTHON_ENV      = PYTHONPATH=$(top_builddir):$(top_builddir)/pyext:$(top_builddir)/pyext/build/ctools/ctools:$(pythondir):$(pyexecdir):$(PYTHONPATH)
+  TEST_PYTHON_CTOOLS     = test_python_ctools.sh
+  TEST_PYTHON_CSCRIPTS   = test_python_cscripts.sh
+  TEST_PYTHON_EXAMPLES   = test_examples.py
+  TEST_PYTHON_COMSCRIPTS = test_python_comscripts.sh
+  TEST_PYTHON_ENV        = PYTHONPATH=$(top_builddir):$(top_builddir)/pyext:$(top_builddir)/cscripts:$(top_builddir)/modules/comscripts:$(top_builddir)/pyext/build/ctools/ctools:$(pythondir):$(pyexecdir):$(PYTHONPATH)
 endif
 
 # Set test environment
 TESTS_ENVIRONMENT = @RUNSHARED@=$(top_builddir)/src/.libs$(TEST_ENV_DIR):$(LIBDIR_GAMMALIB):$(@RUNSHARED@) \
                     $(TEST_PYTHON_ENV) \
-                    TEST_SRCDIR=$(top_srcdir) \
-                    TEST_BUILDDIR=$(top_builddir) \
-                    TEST_DATA=$(top_srcdir)/test/data
+                    TEST_SRCDIR=$(abs_top_srcdir) \
+                    TEST_BUILDDIR=$(abs_top_builddir) \
+                    TEST_DATA=$(abs_top_srcdir)/test/data
 
 # Tests (these are the tests to be executed)
 TESTS = $(TEST_PYTHON_CTOOLS) \
         $(TEST_PYTHON_CSCRIPTS) \
-        $(TEST_PYTHON_EXAMPLES)
+        $(TEST_PYTHON_EXAMPLES) \
+        $(TEST_PYTHON_COMSCRIPTS)
 
 # Create report directory
 all-local:
@@ -78,6 +80,11 @@ installcheck-local:
 	python -c 'import cscripts; cscripts.test()'; \
 	if test "x$$?" != "x0"; then \
 		echo "*** cscripts unit test failure!"; \
+		exit 1; \
+	fi
+	python -c 'import comscripts; comscripts.test()'; \
+	if test "x$$?" != "x0"; then \
+		echo "*** comscripts unit test failure!"; \
 		exit 1; \
 	fi
 endif
